### ISSUE TITLE
Game dont start / stuck gray screen

### ISSUE THREAD

**Issue by xXRainbowXx24** [Admiral-Billy/Pokerogue-App#100]
System : 

RX 6600

Ryzen 5600

16 gb Ram 3200 mhz 

Msi Mpg gaming plus b550

Win 11

//////////////////////////////////

Game dont open when i click on it / im stuck at a grayscreen
![Screenshot_1](https://github.com/Admiral-Billy/Pokerogue-App/assets/110906596/4dfe9ef3-e3e6-4d60-b3ca-ea4888d9445e)
 and it opens multiple task

**Comment by Admiral-Billy** [comment]
First off make sure all of those are closed before launching again, since that'll make saves not work temporarily.

Anyways if you want to get a more specific log of what's going on, go to the folder the game is in, type "cmd" in the address bar at the top, hit enter, type "PokeRogue", and hit enter again. This'll launch the game with the console open and it'll say what's going on potentially; let me know what that says.

Beyond that, make sure you're using the latest version of the app and such, and that might fix things if you aren't.

**Comment by ProxiEx3** [comment]
So I'm having the same problem, just downloaded the most recent version and the game doesn't start (for a WHILE). After clicking the .exe, it takes about 1-2 Minutes until the game actually launches.
If you retry starting it you get multiple tasks like the initial threat stated. Also on the youtube video where I found out about the app, there were many comments about it not starting, so we are not alone!

Nontheless I think pokerogue itself is having problems.. Starting it normaly in the browser doesn't work either right now. Might be too much traffic currently cuz all of the hype.

This is what the cmd command spits out:

[...]\Pokerogue>
Discord Rich Presence is not available! Error: Could not connect
    at Socket.onerror ([...]\Pokerogue\resources\app.asar\node_modules\discord-rpc\src\transports\ipc.js:32:16)
    at Object.onceWrapper (node:events:629:26)
    at Socket.emit (node:events:514:28)
    at emitErrorNT (node:internal/streams/destroy:151:8)
    at emitErrorCloseNT (node:internal/streams/destroy:116:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)

**Comment by xXRainbowXx24** [comment]
My say this:

C:\Users\claus\AppData\Local\Programs\PokeRogue>
Discord Rich Presence is not available! Error: Could not connect
    at Socket.onerror (C:\Users\claus\AppData\Local\Programs\PokeRogue\resources\app.asar\node_modules\discord-rpc\src\transports\ipc.js:32:16)
    at Object.onceWrapper (node:events:629:26)
    at Socket.emit (node:events:514:28)
    at emitErrorNT (node:internal/streams/destroy:151:8)
    at emitErrorCloseNT (node:internal/streams/destroy:116:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21) 
Dont know why my discord rich pressence are not abailable ?

The game now starts on my side but it need min 15min+ and then start it 2 times but the first window close itself after some mins

**Comment by xXRainbowXx24** [comment]
> My say this:
> 
> C:\Users\claus\AppData\Local\Programs\PokeRogue> Discord Rich Presence is not available! Error: Could not connect at Socket.onerror (C:\Users\claus\AppData\Local\Programs\PokeRogue\resources\app.asar\node_modules\discord-rpc\src\transports\ipc.js:32:16) at Object.onceWrapper (node:events:629:26) at Socket.emit (node:events:514:28) at emitErrorNT (node:internal/streams/destroy:151:8) at emitErrorCloseNT (node:internal/streams/destroy:116:3) at process.processTicksAndRejections (node:internal/process/task_queues:82:21) Dont know why my discord rich pressence are not abailable ?
> 
> The game now starts on my side but it need min 15min+ and then start it 2 times but the first window close itself after some mins

EDIT: also now the game need really long to load somthing it is on a nvme m.2 and i know befor that happen i dont had that

**Comment by Admiral-Billy** [comment]
Yeah the Discord Rich Presence alone shouldn't stop the game from starting up, weird. I'll have to see if there's something going on, but it may in fact just be PokeRogue.

**Comment by xXRainbowXx24** [comment]
> Yeah the Discord Rich Presence alone shouldn't stop the game from starting up, weird. I'll have to see if there's something going on, but it may in fact just be PokeRogue.

yea idk i mean i have problems aswell on opera gx there i sit in a gray screen sim

**Comment by xXRainbowXx24** [comment]
i can play now again after some battles the game need really long to load the next fight / the game frezze i guess that btw actullay i have no idea what happen anyway i need to reload the game and that needs then again 15min+- to reload

**Comment by xXRainbowXx24** [comment]
Im in  challenge mode Gen 5 and in the poke select it need very long to load the sprites 
![Screenshot_1](https://github.com/Admiral-Billy/Pokerogue-App/assets/110906596/af64e16c-0c5a-4cc9-b4dc-327eaaa59626)

**Comment by xXRainbowXx24** [comment]
Here my I-net speed maybe it is somthing 
![Screenshot_2](https://github.com/Admiral-Billy/Pokerogue-App/assets/110906596/42ed4f4f-f628-449f-bfd7-4ff785f9436b)

**Comment by xXRainbowXx24** [comment]
> Here my I-net speed maybe it is somthing ![Screenshot_2](https://private-user-images.githubusercontent.com/110906596/340753361-42ed4f4f-f628-449f-bfd7-4ff785f9436b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg3Mjc2NTksIm5iZiI6MTcxODcyNzM1OSwicGF0aCI6Ii8xMTA5MDY1OTYvMzQwNzUzMzYxLTQyZWQ0ZjRmLWY2MjgtNDQ5Zi1iZmQ3LTRmZjc4NWY5NDM2Yi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjE4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYxOFQxNjE1NTlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05MWNlOTQ4YzhhZDUwNTQ3Nzc5OTVlMGMxNDVjZjdiNjgwZTI3OTlhMjVmNDRiOTA1YTJkYjBkZTU0NGNmNmVkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.601ngvKabtc9z5C4KJWEf-u6aokb4CKWjRN9hfBOHPA)

but i can say for sure theats exact the same stats like every day and also pokerouhge runs better

**Comment by Admiral-Billy** [comment]
I'll assume for now the issue is more or less fixed and that it was PokeRogue specific; might just be server load or similar.

**Comment by xXRainbowXx24** [comment]
> I'll assume for now the issue is more or less fixed and that it was PokeRogue specific; might just be server load or similar.

hmm yea i mean i don't know either like when i can play it on the internet site it was so cool but self there i cant play it.

Microsoft Windows [Version 10.0.22631.3737]
(c) Microsoft Corporation. Alle Rechte vorbehalten.

B:\PokeRogue>PokeRogue

B:\PokeRogue>
[11404:0619/001658.736:ERROR:cache_util_win.cc(20)] Unable to move the cache: Zugriff verweigert (0x5)
[11404:0619/001658.736:ERROR:cache_util_win.cc(20)] Unable to move the cache: Zugriff verweigert (0x5)
Discord Rich Presence is not available! Error: Could not connect
    at Socket.onerror (B:\PokeRogue\resources\app.asar\node_modules\discord-rpc\src\transports\ipc.js:32:16)
    at Object.onceWrapper (node:events:629:26)
    at Socket.emit (node:events:514:28)
    at emitErrorNT (node:internal/streams/destroy:151:8)
    at emitErrorCloseNT (node:internal/streams/destroy:116:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
[11404:0619/001658.742:ERROR:disk_cache.cc(208)] Unable to create cache
[11404:0619/001658.742:ERROR:gpu_disk_cache.cc(708)] Gpu Cache Creation failed: -2
[11404:0619/001658.742:ERROR:disk_cache.cc(208)] Unable to create cache
[11404:0619/001658.742:ERROR:gpu_disk_cache.cc(708)] Gpu Cache Creation failed: -2
[9804:0619/001658.750:ERROR:cache_util_win.cc(20)] Unable to move the cache: Zugriff verweigert (0x5)
[9804:0619/001658.750:ERROR:disk_cache.cc(208)] Unable to create cache
[11404:0619/001701.731:ERROR:service_worker_storage.cc(2016)] Failed to delete the database: Database IO error

**Comment by xXRainbowXx24** [comment]
> > I'll assume for now the issue is more or less fixed and that it was PokeRogue specific; might just be server load or similar.
> 
> hmm yea i mean i don't know either like when i can play it on the internet site it was so cool but self there i cant play it.
> 
> Microsoft Windows [Version 10.0.22631.3737] (c) Microsoft Corporation. Alle Rechte vorbehalten.
> 
> B:\PokeRogue>PokeRogue
> 
> B:\PokeRogue> [11404:0619/001658.736:ERROR:cache_util_win.cc(20)] Unable to move the cache: Zugriff verweigert (0x5) [11404:0619/001658.736:ERROR:cache_util_win.cc(20)] Unable to move the cache: Zugriff verweigert (0x5) Discord Rich Presence is not available! Error: Could not connect at Socket.onerror (B:\PokeRogue\resources\app.asar\node_modules\discord-rpc\src\transports\ipc.js:32:16) at Object.onceWrapper (node:events:629:26) at Socket.emit (node:events:514:28) at emitErrorNT (node:internal/streams/destroy:151:8) at emitErrorCloseNT (node:internal/streams/destroy:116:3) at process.processTicksAndRejections (node:internal/process/task_queues:82:21) [11404:0619/001658.742:ERROR:disk_cache.cc(208)] Unable to create cache [11404:0619/001658.742:ERROR:gpu_disk_cache.cc(708)] Gpu Cache Creation failed: -2 [11404:0619/001658.742:ERROR:disk_cache.cc(208)] Unable to create cache [11404:0619/001658.742:ERROR:gpu_disk_cache.cc(708)] Gpu Cache Creation failed: -2 [9804:0619/001658.750:ERROR:cache_util_win.cc(20)] Unable to move the cache: Zugriff verweigert (0x5) [9804:0619/001658.750:ERROR:disk_cache.cc(208)] Unable to create cache [11404:0619/001701.731:ERROR:service_worker_storage.cc(2016)] Failed to delete the database: Database IO error

B:\PokeRogue>
[14532:0619/002956.722:ERROR:cache_util_win.cc(20)] Unable to move the cache: Zugriff verweigert (0x5)
[14532:0619/002956.722:ERROR:cache_util_win.cc(20)] Unable to move the cache: Zugriff verweigert (0x5)
[14532:0619/002956.726:ERROR:disk_cache.cc(208)] Unable to create cache
[14532:0619/002956.726:ERROR:gpu_disk_cache.cc(708)] Gpu Cache Creation failed: -2
[14532:0619/002956.726:ERROR:disk_cache.cc(208)] Unable to create cache
[14532:0619/002956.726:ERROR:gpu_disk_cache.cc(708)] Gpu Cache Creation failed: -2
[21344:0619/002956.737:ERROR:cache_util_win.cc(20)] Unable to move the cache: Zugriff verweigert (0x5)
[21344:0619/002956.737:ERROR:disk_cache.cc(208)] Unable to create cache
Discord Rich Presence is ready!
[14532:0619/002959.720:ERROR:service_worker_storage.cc(2016)] Failed to delete the database: Database IO error
(node:14532) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 did-stop-loading listeners added to [WebContents]. Use emitter.setMaxListeners() to increase limit
(Use `PokeRogue --trace-warnings ...` to show where the warning was created) 

Found out why it says Discord Rich Presence is not available! Error: Could not connect its becuase i run discord as admin

**Comment by xXRainbowXx24** [comment]
B:\PokeRogue>
[20768:0619/003314.278:ERROR:cache_util_win.cc(20)] Unable to move the cache: Zugriff verweigert (0x5)
[20768:0619/003314.278:ERROR:cache_util_win.cc(20)] Unable to move the cache: Zugriff verweigert (0x5)
[20768:0619/003314.282:ERROR:disk_cache.cc(208)] Unable to create cache
[20768:0619/003314.282:ERROR:gpu_disk_cache.cc(708)] Gpu Cache Creation failed: -2
[20768:0619/003314.282:ERROR:disk_cache.cc(208)] Unable to create cache
[20768:0619/003314.282:ERROR:gpu_disk_cache.cc(708)] Gpu Cache Creation failed: -2
[18476:0619/003314.296:ERROR:cache_util_win.cc(20)] Unable to move the cache: Zugriff verweigert (0x5)
[18476:0619/003314.296:ERROR:disk_cache.cc(208)] Unable to create cache
Discord Rich Presence is ready!
[20768:0619/003317.289:ERROR:service_worker_storage.cc(2016)] Failed to delete the database: Database IO error
(node:20768) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 did-stop-loading listeners added to [WebContents]. Use emitter.setMaxListeners() to increase limit
    at _addListener (node:events:588:17)
    at WebContents.addListener (node:events:606:10)
    at WebContents.once (node:events:650:8)
    at node:electron/js2c/browser_init:2:70069
    at new Promise (<anonymous>)
    at waitTillCanExecuteJavaScript (node:electron/js2c/browser_init:2:70056)
    at _.executeJavaScript (node:electron/js2c/browser_init:2:70273)
    at Timeout.updateDiscordPresence [as _onTimeout] (B:\PokeRogue\resources\app.asar\src\main.js:120:44)
    at listOnTimeout (node:internal/timers:573:17)
